[build]
target-dir = "../../../.cargo-target/desktop"

[target.aarch64-linux-android]
linker = "E:\\Android\\Sdk\\ndk\\29.0.13846066\\toolchains\\llvm\\prebuilt\\windows-x86_64\\bin\\aarch64-linux-android35-clang.cmd"
